# https://school.programmers.co.kr/learn/courses/30/lessons/131115

-- 1
SELECT * FROM FOOD_PRODUCT
WHERE PRICE = 
(
SELECT MAX(PRICE) FROM FOOD_PRODUCT
)

-- 2
SELECT * FROM FOOD_PRODUCT
ORDER BY PRICE DESC
LIMIT 1
