# https://school.programmers.co.kr/learn/courses/30/lessons/301647

SELECT ED.ID, ED.GENOTYPE, EDP.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA ED
INNER JOIN ECOLI_DATA EDP
ON EDP.ID = ED.PARENT_ID
WHERE ED.GENOTYPE & EDP.GENOTYPE = EDP.GENOTYPE
ORDER BY ED.ID ASC
