# https://school.programmers.co.kr/learn/courses/30/lessons/273711
# sub query
SELECT IT.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_TREE IT
JOIN ITEM_INFO II ON IT.ITEM_ID = II.ITEM_ID
WHERE IT.PARENT_ITEM_ID IN
(
    SELECT II.ITEM_ID FROM ITEM_INFO II
    WHERE II.RARITY = "RARE"
)
ORDER BY IT.ITEM_ID DESC
