# https://school.programmers.co.kr/learn/courses/30/lessons/298518

SELECT COUNT(FI.FISH_TYPE) AS FISH_COUNT
FROM FISH_NAME_INFO FN
JOIN FISH_INFO FI ON FN.FISH_TYPE = FI.FISH_TYPE
WHERE FI.FISH_TYPE IN
(
    SELECT FISH_TYPE FROM FISH_NAME_INFO
    WHERE FISH_NAME = "BASS" OR FISH_NAME = "SNAPPER"
)
